# =============================================================================
# RTR (Real Time Rice) Package
# =============================================================================
# Integrates Real Time Rice prediction data into PaddiSense.
# Data fetching/parsing is handled by custom_components/paddisense/rtr/
# This package provides the automation for scheduled refreshes.
# =============================================================================

# -----------------------------------------------------------------------------
# SHELL COMMANDS
# -----------------------------------------------------------------------------
shell_command:
  # Read RTR version from file
  rtr_version: "cat /config/PaddiSense/rtr/VERSION 2>/dev/null || echo 'unknown'"

# -----------------------------------------------------------------------------
# COMMAND LINE SENSORS
# -----------------------------------------------------------------------------
command_line:
  # RTR module version from VERSION file
  - sensor:
      name: "RTR Module Version"
      unique_id: rtr_module_version
      command: "cat /config/PaddiSense/rtr/VERSION 2>/dev/null || echo 'unknown'"
      scan_interval: 86400

# -----------------------------------------------------------------------------
# AUTOMATIONS
# -----------------------------------------------------------------------------
automation:
  # Daily RTR data refresh at 6am
  - id: rtr_daily_refresh
    alias: "RTR Daily Refresh"
    description: "Refresh Real Time Rice data daily at 6am"
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      # Only run if RTR is configured
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.paddisense_real_time_rice
            state: "Not configured"
    action:
      - service: paddisense.refresh_rtr_data
    mode: single

  # Refresh RTR on Home Assistant start (if configured)
  - id: rtr_startup_refresh
    alias: "RTR Startup Refresh"
    description: "Refresh RTR data on Home Assistant startup"
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.paddisense_real_time_rice
            state: "Not configured"
    action:
      # Delay to allow entities to load
      - delay:
          minutes: 2
      - service: paddisense.refresh_rtr_data
    mode: single

# -----------------------------------------------------------------------------
# INPUT HELPERS
# -----------------------------------------------------------------------------
input_text:
  rtr_url_input:
    name: RTR URL Input
    icon: mdi:link
    max: 255
    initial: ""

# -----------------------------------------------------------------------------
# SCRIPTS
# -----------------------------------------------------------------------------
script:
  rtr_refresh_data:
    alias: RTR Refresh Data
    icon: mdi:refresh
    mode: single
    sequence:
      - service: paddisense.refresh_rtr_data

  rtr_set_url:
    alias: RTR Set URL
    icon: mdi:link-plus
    mode: single
    sequence:
      - variables:
          url: "{{ states('input_text.rtr_url_input') | trim }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ url == '' }}"
            sequence:
              - service: persistent_notification.create
                data:
                  title: "Real Time Rice"
                  message: "Please enter a URL first."
              - stop: "No URL"
      - service: paddisense.set_rtr_url
        data:
          url: "{{ url }}"
      - delay: "00:00:01"
      - service: paddisense.refresh_rtr_data
      - service: input_text.set_value
        target:
          entity_id: input_text.rtr_url_input
        data:
          value: ""
      - service: persistent_notification.create
        data:
          title: "Real Time Rice"
          message: "RTR URL saved and data refreshed."
