#!/bin/bash
#
# PaddiSense Installer
# ====================
# Installs PaddiSense modules for Home Assistant
#
# Usage:
#   Fresh install from git:
#     git clone https://github.com/YOUR_USER/paddisense.git /config/PaddiSense
#     cp PaddiSense/server.yaml.example server.yaml  # Edit this!
#     ./PaddiSense/install.sh
#
#   Install specific module:
#     ./PaddiSense/install.sh ipm
#     ./PaddiSense/install.sh asm
#     ./PaddiSense/install.sh weather
#     ./PaddiSense/install.sh pwm
#
#   Install all enabled modules from server.yaml:
#     ./PaddiSense/install.sh
#

set -e

CONFIG_DIR="/config"
INSTALL_DIR="$CONFIG_DIR/PaddiSense"
PACKAGES_DIR="$INSTALL_DIR/packages"
DATA_DIR="$CONFIG_DIR/local_data"
SERVER_CONFIG="$CONFIG_DIR/server.yaml"
LOVELACE_FILE="$CONFIG_DIR/lovelace_dashboards.yaml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print functions
print_header() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  PaddiSense Installer${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
}

print_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_info() {
    echo -e "    $1"
}

# Function to read version from file
get_version() {
    local version_file="$1"
    if [ -f "$version_file" ]; then
        cat "$version_file" | tr -d '\n'
    else
        echo "unknown"
    fi
}

# Function to check if module is enabled in server.yaml
is_module_enabled() {
    local module="$1"
    if [ -f "$SERVER_CONFIG" ]; then
        # Parse YAML - look for "module: true" pattern
        grep -E "^\s*${module}:\s*(true|yes)" "$SERVER_CONFIG" > /dev/null 2>&1
        return $?
    fi
    return 1
}

# Function to get dashboard metadata for a module
# Returns: slug|title|icon|filename
get_dashboard_meta() {
    local module="$1"
    case "$module" in
        ipm)
            echo "ipm-inventory|Inventory Manager|mdi:warehouse|PaddiSense/ipm/dashboards/inventory.yaml"
            ;;
        asm)
            echo "asm-service|Asset Service Manager|mdi:tractor|PaddiSense/asm/dashboards/views.yaml"
            ;;
        weather)
            echo "weather-station|Weather|mdi:weather-cloudy|PaddiSense/weather/dashboards/views.yaml"
            ;;
        pwm)
            echo "pwm-irrigation|Water Management|mdi:water|PaddiSense/pwm/dashboards/views.yaml"
            ;;
        *)
            echo ""
            ;;
    esac
}

# Function to create/update package symlinks
setup_package_symlinks() {
    print_step "Setting up package symlinks..."
    mkdir -p "$PACKAGES_DIR"

    for mod in ipm asm weather pwm; do
        local target="../$mod/package.yaml"
        local link="$PACKAGES_DIR/$mod.yaml"

        if [ -f "$INSTALL_DIR/$mod/package.yaml" ]; then
            # Remove existing symlink/file if it exists
            rm -f "$link" 2>/dev/null || true
            # Create new symlink
            ln -sf "$target" "$link"
        fi
    done

    print_info "Package symlinks in: $PACKAGES_DIR/"
}

# Function to generate lovelace_dashboards.yaml
generate_lovelace_dashboards() {
    print_step "Generating lovelace_dashboards.yaml..."

    # Start the YAML file
    cat > "$LOVELACE_FILE" << 'EOF'
# Auto-generated by PaddiSense install.sh
# Do not edit manually - changes will be overwritten
# To add/remove dashboards, edit server.yaml and run ./PaddiSense/install.sh

EOF

    local first=true
    for m in "${INSTALLED_MODULES[@]}"; do
        local mod=$(echo "$m" | cut -d: -f1)
        local meta=$(get_dashboard_meta "$mod")

        if [ -n "$meta" ]; then
            local slug=$(echo "$meta" | cut -d'|' -f1)
            local title=$(echo "$meta" | cut -d'|' -f2)
            local icon=$(echo "$meta" | cut -d'|' -f3)
            local filename=$(echo "$meta" | cut -d'|' -f4)

            cat >> "$LOVELACE_FILE" << EOF
$slug:
  mode: yaml
  title: $title
  icon: $icon
  show_in_sidebar: true
  filename: $filename

EOF
        fi
    done

    print_info "Dashboard config: $LOVELACE_FILE"
}

# Function to install a module
install_module() {
    local module="$1"
    local module_dir="$INSTALL_DIR/$module"
    local data_dir="$DATA_DIR/$module"

    if [ ! -d "$module_dir" ]; then
        print_error "Module not found: $module_dir"
        return 1
    fi

    local version=$(get_version "$module_dir/VERSION")
    echo ""
    print_step "Installing $module v$version"

    # Create data directory if module uses one
    if [ "$module" = "ipm" ] || [ "$module" = "asm" ] || [ "$module" = "weather" ] || [ "$module" = "pwm" ]; then
        mkdir -p "$data_dir"
        mkdir -p "$data_dir/backups"
        print_info "Data directory: $data_dir"
    fi

    # Set permissions on Python scripts
    if [ -d "$module_dir/python" ]; then
        chmod +x "$module_dir/python/"*.py 2>/dev/null || true
    fi

    # Module-specific setup
    case "$module" in
        weather)
            # Create weather_api data directory for API stations
            mkdir -p "$DATA_DIR/weather_api"
            print_info "Unified weather module supports:"
            print_info "  - Local Ecowitt gateway (auto-detected)"
            print_info "  - Remote API stations (requires API credentials)"
            if ! grep -q "ecowitt_app_key" "$CONFIG_DIR/secrets.yaml" 2>/dev/null; then
                print_warn "For API stations: add ecowitt_app_key to secrets.yaml"
            fi
            if ! grep -q "ecowitt_api_key" "$CONFIG_DIR/secrets.yaml" 2>/dev/null; then
                print_warn "For API stations: add ecowitt_api_key to secrets.yaml"
            fi
            ;;
        pwm)
            print_info "PWM module requires:"
            print_info "  - Farm configuration in server.yaml"
            print_info "  - ESPHome devices with water depth sensors"
            print_info "  - Paddocks/bays configured via dashboard Settings"
            if ! grep -qE "^\s*pwm:" "$SERVER_CONFIG" 2>/dev/null; then
                print_warn "Configure pwm.farms section in server.yaml"
            fi
            ;;
    esac

    INSTALLED_MODULES+=("$module:v$version")
}

# Parse command line
MODULE="${1:-}"

print_header

# Check we're in the right place
if [ ! -f "$CONFIG_DIR/configuration.yaml" ]; then
    print_error "configuration.yaml not found in $CONFIG_DIR"
    echo "    Please run from your Home Assistant config directory"
    exit 1
fi

if [ ! -d "$INSTALL_DIR" ]; then
    print_error "PaddiSense not found in $INSTALL_DIR"
    echo "    Clone the repository first:"
    echo "    git clone https://github.com/YOUR_USER/paddisense.git $INSTALL_DIR"
    exit 1
fi

# Track what we install
INSTALLED_MODULES=()

# Determine what to install
if [ -n "$MODULE" ]; then
    # Specific module requested
    echo ""
    print_step "Installing specific module: $MODULE"
    install_module "$MODULE"
else
    # Install based on server.yaml
    if [ -f "$SERVER_CONFIG" ]; then
        echo ""
        print_step "Reading configuration from server.yaml"

        for mod in ipm asm weather pwm; do
            if is_module_enabled "$mod"; then
                install_module "$mod"
            fi
        done
    else
        # No server.yaml - install defaults (ipm and asm)
        print_warn "No server.yaml found - installing default modules (ipm, asm)"
        echo ""
        print_info "Create server.yaml for custom module selection:"
        print_info "  cp PaddiSense/server.yaml.example server.yaml"

        install_module "ipm"
        install_module "asm"
    fi
fi

# Set script permissions
chmod +x "$INSTALL_DIR/"*.sh 2>/dev/null || true

# Summary
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Installation Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""

if [ ${#INSTALLED_MODULES[@]} -eq 0 ]; then
    print_warn "No modules were installed"
    echo ""
    echo "Enable modules in server.yaml or specify a module:"
    echo "  ./PaddiSense/install.sh ipm"
    exit 0
fi

# Setup package symlinks and generate lovelace dashboards
setup_package_symlinks
generate_lovelace_dashboards

echo ""
echo "Installed modules:"
for m in "${INSTALLED_MODULES[@]}"; do
    echo "  - $m"
done

# Check if configuration.yaml needs updating
CONFIG_NEEDS_UPDATE=false
if ! grep -q "!include_dir_named PaddiSense/packages" "$CONFIG_DIR/configuration.yaml" 2>/dev/null; then
    CONFIG_NEEDS_UPDATE=true
fi
if ! grep -q "!include lovelace_dashboards.yaml" "$CONFIG_DIR/configuration.yaml" 2>/dev/null; then
    CONFIG_NEEDS_UPDATE=true
fi

if [ "$CONFIG_NEEDS_UPDATE" = true ]; then
    echo ""
    echo -e "${YELLOW}One-time configuration.yaml update required:${NC}"
    echo ""
    echo "Replace your PaddiSense section with:"
    echo ""
    echo "homeassistant:"
    echo "  packages: !include_dir_named PaddiSense/packages/"
    echo ""
    echo "lovelace:"
    echo "  mode: storage"
    echo "  dashboards: !include lovelace_dashboards.yaml"
    echo ""
    echo -e "${GREEN}After this change, new modules are auto-registered!${NC}"
    echo "Just enable in server.yaml and run ./PaddiSense/install.sh"
fi

echo ""
echo -e "${YELLOW}Required HACS frontend cards:${NC}"
echo "  - button-card"
echo "  - card-mod"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
if [ "$CONFIG_NEEDS_UPDATE" = true ]; then
    echo "  1. Update configuration.yaml (one-time setup - see above)"
    echo "  2. Install required HACS cards"
    echo "  3. Restart Home Assistant"
    echo "  4. Open each dashboard and click 'Initialize System' in Settings"
else
    echo "  1. Restart Home Assistant to apply changes"
    echo "  2. Open each dashboard and click 'Initialize System' in Settings"
fi
echo ""
